version: "3"
services:
  web:
    build:
      context: .
    container_name: web
    ports:
      - "80:8080"
    environment:
      - AWS_region=us-east-1
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
