version: "2"
services:
  web123:
    build:
      context: .
    container_name: web
    ports:
      - "80:5000"
    depends_on:
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
